mule.keystore.path: "keystore/Holcim-Mule-prd-KeyStore.p12"
mule.keystore.alias: keystore-cd-prod
mule.keystore.pwd: "![x15JdCtCXvEnVqy73b9m1w==]"
mulepassword: "![g/3F24kJXHRq4Gu9Mp6spNxQHCKFdzzCYbF3QV8Aze1E03n6Z7EXSr9XaAZASc4i]"

client_id: "![PnSf/bEkw7fPErn8CEKWru6+YBRRvwLqGizv0OU5WeRjCmFhDzpGAaCotRmPwCv1]"
IND.X-RSM-int-api-key : "![DOfjofDzJZuz1mfvSTzH8PldNGtapgL1xVYMXblhT3fPtQGnDDQ3Sd3NMwES9UtPaSWYlp22b1vRZ8UaH0z7s2lkK0NSNRQxSPhQXf1G+qI=]"
UK1.X-RSM-int-api-key: "![jxIHT0IZjB1gKoBHOfyP1JLAd4rL7YrxosN6Mb6bEkqTjrt/xK3rnr9bgEYJF6xgs/ng2nJ1P1pXp9C2l06sbrxD2N8qMRGkC8hkQZMPH6s=]"
SV.X-RSM-int-api-key: "![omtMZZ4eZbtIA1mfc/453sZYasNkSsyEmt0+2W+uy72hU7fouYYu8IM8w2RsbYGvwprHt9CYagrNfja+78nJSFMclC3niYYL3QowprawasQ=]"
EC.X-RSM-int-api-key: "![k1tpHGVDczXIrwaxrfEEB67ufaugGBevm8mGoSwzZxlUZkKYO3vL4w1Zl0vGMbRdNN60wSIwvF6zRaNNoAAlrm5RY0fM71VLGxMXX/QN7KQ=]"
CO.X-RSM-int-api-key: "![EvcgG0wnK7hCv4FwXUJZrXlqrCezX5Xnyuc16D+hJhokbV/6C97LXs/7MHt+y37irtm4OaffmmPDJJxjM3RKB5lVBUhdPC1OpivocwZSBLY=]"
cd.host: "production.kubikapp.com"
api2.basePath: "/api/integration/v2"

SQSTestQueueARN: "arn:aws:sqs:eu-west-1:944927062928:cd-mulesoft-pd-error"
SQSAccessKey: "AKIA5YAQKXOIKCQPIFZJ"
SQSSecretKey: "![0y3Db6vBoSxeqDE4sxtYI1MNk2uWGlvfS+BlplJN3Gx40MryA61i73bQf0KSe1aP]"
SQSQueueURL: "https://sqs.eu-west-1.amazonaws.com/944927062928/cd-mulesoft-pd-error"

cloudhub.username: "Concrete-Direct-CICD"
cloudhub.pwd: "![/GE+rQDJWaSEJA8T0bEAypWRqardGArjM6aJ37nMx2M=]"
cloudhub.env: "afc1d43b-108a-4b07-89d2-5c9704a9e325"
cloudhub.domain: "api-2-common-cd-md-gateway"